language: node_js
node_js:
  - "0.10"

before_install:
  - npm install

script: npm test

services:
  - mongodb

env:
  - AUTH_SECRET=superSecretAuth MONGOLAB_URI=mongodb://localhost/user_development
